image:
  repository: victoriametrics/victoria-metrics
  tag: "v1.135.0"
  pullPolicy: IfNotPresent

retentionPeriod: "1"

port: 8428

storage:
  size: 10Gi
  storageClass: "longhorn"

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

service:
  type: ClusterIP
  port: 8428