apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ad-otel-victorialogs
  namespace: ad-otel
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}