apiVersion: v1
kind: Service
metadata:
  name: ad-otel-victoriametrics
  namespace: ad-otel
spec:
  type: {{ .Values.service.type }}
  selector:
    app: ad-otel-victoriametrics
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.port }}