apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ad-otel-victorialogs
  namespace: argocd
  labels:
    project: ad-otel
    component: victorialogs
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://otel.git
    targetRevision: HEAD
    path: helm/victorialogs
  destination:
    server: https://kubernetes.default.svc
    namespace: ad-otel
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true